#!/usr/bin/env python3
"""THE ICONS OF MANTRA TRAIL (27.9.2026). One line style: 24 x 24, stroke 1.8, round ends, no fill.
Each is written here once and made twice: design/icons/<name>.svg, to see and edit anywhere, and
app/src/main/res/drawable/ic_<name>.xml, Android's own vector format, which the app draws tinted.
Run: python3 design/make_icons.py"""
import pathlib
ROOT = pathlib.Path(__file__).resolve().parent.parent
ICONS = {
    "plus": "M12 5v14 M5 12h14",
    "minus": "M5 12h14",
    "parcels": "M4 4h16v16H4z M4 11h8 M12 4v16 M12 15h8",
    "layers": "M12 3l9 5-9 5-9-5z M3 13l9 5 9-5",
    "settings": "M18.82 10.43 L21.11 10.72 L21.11 13.28 L18.82 13.57 L17.94 15.71 L19.35 17.54 L17.54 19.35 L15.71 17.94 L13.57 18.82 L13.28 21.11 L10.72 21.11 L10.43 18.82 L8.29 17.94 L6.46 19.35 L4.65 17.54 L6.06 15.71 L5.18 13.57 L2.89 13.28 L2.89 10.72 L5.18 10.43 L6.06 8.29 L4.65 6.46 L6.46 4.65 L8.29 6.06 L10.43 5.18 L10.72 2.89 L13.28 2.89 L13.57 5.18 L15.71 6.06 L17.54 4.65 L19.35 6.46 L17.94 8.29z M12 9a3 3 0 1 0 0 6a3 3 0 1 0 0-6z",
    "pin": "M12 21s-6.5-5.8-6.5-11.2a6.5 6.5 0 1 1 13 0c0 5.4-6.5 11.2-6.5 11.2z M12 7.8a2 2 0 1 0 0 4a2 2 0 1 0 0-4z",
    "search": "M10.5 4.5a6 6 0 1 0 0 12a6 6 0 1 0 0-12z M15 15l5 5",
    "close": "M6 6l12 12 M18 6L6 18",
    "copy": "M9 9h10v11H9z M5 15V4h10",
    "text": "M6 3h8l4 4v14H6z M14 3v4h4 M9 12h6 M9 16h6",
    "check": "M5 12.5l4.5 4.5L19 7",
    "chevron": "M9 6l6 6-6 6",
    "chevron_down": "M6 9l6 6 6-6",
    "trash": "M4 7h16 M9 7V4h6v3 M6 7l1 13h10l1-13",
    "mountain": "M3 19l6-10 4 6 3-4 5 8z",
    "globe": "M12 3a9 9 0 1 0 0 18a9 9 0 1 0 0-18z M3 12h18 M12 3c3 3 3 15 0 18 M12 3c-3 3-3 15 0 18",
    "filter": "M4 5h16l-6 7v6l-4 2v-8z",
    "save": "M12 4v11 M7 10l5 5 5-5 M5 20h14",
    "track": "M5 19a2 2 0 1 0 0.01 0z M5 17c0-4 5-3 6-7s-2-5 1-6 7 1 7 1 M19 5a1.5 1.5 0 1 0 0.01 0z",
    "key": "M8 8a4 4 0 1 0 0 8a4 4 0 1 0 0-8z M12 12h9 M18 12v3 M21 12v2",
    "info": "M12 3a9 9 0 1 0 0 18a9 9 0 1 0 0-18z M12 11v5 M12 8h0.01",
    "route": "M6 5a2 2 0 1 0 0 4a2 2 0 1 0 0-4z M18 15a2 2 0 1 0 0 4a2 2 0 1 0 0-4z M8 7h7a3 3 0 0 1 0 6H9a3 3 0 0 0 0 6h7",
    "edit": "M4 20h4L18.5 9.5l-4-4L4 16z M13 7l4 4",
    "eye": "M2 12s3.6-6.5 10-6.5S22 12 22 12s-3.6 6.5-10 6.5S2 12 2 12z M12 9a3 3 0 1 0 0 6a3 3 0 1 0 0-6z",
    "eye_off": "M2 12s3.6-6.5 10-6.5S22 12 22 12s-3.6 6.5-10 6.5S2 12 2 12z M12 9a3 3 0 1 0 0 6a3 3 0 1 0 0-6z M4 4l16 16",
    "play": "M7 5l12 7-12 7z",
    "folder": "M3 6h6l2 2h10v11H3z",
    "satellite": "M9 9l6 6 M3.5 8.5l5-5 3 3-5 5z M12.5 17.5l5-5 3 3-5 5z M10.5 10.5l3 3 M15 5a4 4 0 0 1 4 4 M15 2a7 7 0 0 1 7 7",
}
SVG = '''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="{d}"/></svg>
'''
XML = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/make_icons.py from design/icons/{name}.svg. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp" android:height="24dp"
    android:viewportWidth="24" android:viewportHeight="24">
    <path android:pathData="{d}"
        android:fillColor="#00000000" android:strokeColor="#FFFFFFFF" android:strokeWidth="1.8"
        android:strokeLineCap="round" android:strokeLineJoin="round" />
</vector>
'''
for name, d in ICONS.items():
    (ROOT / "design/icons" / f"{name}.svg").write_text(SVG.format(d=d))
    (ROOT / "app/src/main/res/drawable" / f"ic_{name}.xml").write_text(XML.format(name=name, d=d))
print(f"{len(ICONS)} icons written")
